@HostUri = http://localhost:5074
@IdentityHost = http://localhost:5002

@MovieId = --
@Slug = --

@AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkYTIyNjUyMC01MTZlLTQyODQtODExZi03MWIzYmMwNDI0OTciLCJzdWIiOiJzb21lb25lQHNvbWVkb21haW4uY29tIiwiZW1haWwiOiJzb21lb25lQHNvbWVkb21haW4uY29tIiwidXNlcmlkIjoiZDg1NjZkZTMtYjFhNi00YTliLWI4NDItOGUzODg3YTgyZTQxIiwiYWRtaW4iOnRydWUsInRydXN0ZWRfbWVtYmVyIjp0cnVlLCJuYmYiOjE3NjM4MDQyNTMsImV4cCI6MTc2MzgzMzA1MywiaWF0IjoxNzYzODA0MjUzLCJpc3MiOiJodHRwczovL2lkLnNvbWVwcm92aWRlci5jb20iLCJhdWQiOiJodHRwczovL21vdmllcy5zb21lZG9tYWluLmNvbSJ9.qRI7e-RFX8BYFkI-u2w3fEi0W8rYRsgpNLWK3fpX3Ko

###
# group: Identity
# 👉 NOTE: Run Identity.Api project separately in order to use it 
# @name Token Generator
POST {{IdentityHost}}/token
Content-Type: application/json

{
  "userid": "d8566de3-b1a6-4a9b-b842-8e3887a82e41",
  "email": "someone@somedomain.com",
  "customClaims": {
    "admin": true,
    "trusted_member": true
  }
}

###
# group: Movies
# @name Create movie
POST {{HostUri}}/api/movies
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "Title": "Some movie name",
  "YearOfRelease": 2023,
  "Genres": [
    "Comedy"
  ]
}

###
# group: Movies
# @name Get movie by Id
GET {{HostUri}}/api/movies/{{MovieId}}

###
# group: Movies
# @name Get movie by Slug
GET {{HostUri}}/api/movies/{{Slug}}

###
# group: Movies
# @name Get all movies
GET {{HostUri}}/api/movies

###
# group: Movies
# @name Update movie
PUT {{HostUri}}/api/movies/{{MovieId}}
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "Title": "Some movie name",
  "YearOfRelease": 2023,
  "Genres": [
    "Comedy",
    "Action"
  ]
}

###
# group: Movies
# @name Delete movie
DELETE {{HostUri}}/api/movies/{{MovieId}}
Authorization: Bearer {{AuthToken}}

###
# group: Ratings
# @name Rate movie
PUT {{HostUri}}/api/movies/{{MovieId}}/ratings
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "rating": 5
}

###
# group: Ratings
# @name Get my ratings
GET {{HostUri}}/api/ratings/me
Authorization: Bearer {{AuthToken}}

###
# group: Ratings
# @name Delete rating
DELETE {{HostUri}}/api/movies/{{MovieId}}/ratings
Authorization: Bearer {{AuthToken}}